-- ============================================================
-- MIGRATIE: Persoon ID naar Numeriek (Auto-increment)
-- ============================================================

-- Stap 1: Schakel foreign key checks even uit (indien nodig, in Supabase vaak niet nodig via UI, maar safe in SQL)
-- In Supabase/Postgres doen we dit door de constraints te droppen en later terug te zetten.

-- Stap 2: Voeg een tijdelijke kolom toe om de Smartschool ID's te bewaren
ALTER TABLE persoon ADD COLUMN IF NOT EXISTS ss_id TEXT;

-- Stap 3: Kopieer de huidige tekst-ID naar ss_id (voor leerlingen die al ingelogd hebben)
UPDATE persoon SET ss_id = id WHERE ss_id IS NULL;

-- Stap 4: Verwijder de primary key constraint op persoon.id
-- Hiervoor moeten we eerst de foreign keys in andere tabellen droppen.
ALTER TABLE reservering DROP CONSTRAINT IF EXISTS reservering_persoon_id_fkey;
ALTER TABLE log DROP CONSTRAINT IF EXISTS log_persoon_id_fkey;

-- Stap 5: Verander de id kolom van persoon naar numeriek met auto-increment
-- Dit is lastig direct te doen op een PK kolom met data. 
-- De veiligste manier is: een nieuwe id kolom maken en de oude weggooien.

ALTER TABLE persoon RENAME COLUMN id TO old_id;
ALTER TABLE persoon ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Stap 6: Update de foreign keys in reservering en log
-- We moeten de tekst-ID's daar ook omzetten naar de nieuwe numerieke ID's
ALTER TABLE reservering ADD COLUMN persoon_id_new BIGINT;
UPDATE reservering r SET persoon_id_new = p.id FROM persoon p WHERE r.persoon_id = p.old_id;

ALTER TABLE log ADD COLUMN persoon_id_new BIGINT;
UPDATE log l SET persoon_id_new = p.id FROM persoon p WHERE l.persoon_id = p.old_id;

-- Stap 7: Maak de nieuwe ID de primary key
ALTER TABLE persoon DROP COLUMN old_id;
ALTER TABLE persoon ADD PRIMARY KEY (id);

-- Stap 8: Maak de foreign key kolommen definitief
ALTER TABLE reservering DROP COLUMN persoon_id;
ALTER TABLE reservering RENAME COLUMN persoon_id_new TO persoon_id;
ALTER TABLE reservering ADD CONSTRAINT reservering_persoon_id_fkey FOREIGN KEY (persoon_id) REFERENCES persoon(id) ON DELETE CASCADE;

ALTER TABLE log DROP COLUMN persoon_id;
ALTER TABLE log RENAME COLUMN persoon_id_new TO persoon_id;
ALTER TABLE log ADD CONSTRAINT log_persoon_id_fkey FOREIGN KEY (persoon_id) REFERENCES persoon(id) ON DELETE CASCADE;

-- Stap 9: Optioneel: Maak ss_id uniek (om dubbele koppelingen te voorkomen)
CREATE UNIQUE INDEX IF NOT EXISTS idx_persoon_ss_id ON persoon(ss_id) WHERE ss_id IS NOT NULL;

-- ============================================================
-- UPDATE RPC'S (indien ze TEXT verwachten voor persoon_id)
-- ============================================================

-- We passen de claim_kamer functie aan om BIGINT te accepteren voor p_persoon_id
-- (Eerst droppen we de oude die TEXT verwacht)
DROP FUNCTION IF EXISTS claim_kamer(BIGINT, TEXT, BIGINT);
CREATE OR REPLACE FUNCTION claim_kamer(
    p_kamer_id BIGINT,
    p_persoon_id BIGINT,
    p_hotel_id BIGINT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
-- ... (Inhoud blijft hetzelfde, alleen type p_persoon_id verandert)
DECLARE
    v_capaciteit INT;
    v_bezet INT;
    v_bestaand INT;
    v_has_pending INT;
    v_res_id TEXT;
    v_server_ts BIGINT;
BEGIN
    v_server_ts := (extract(epoch from now()) * 1000)::bigint;
    SELECT capaciteit INTO v_capaciteit FROM kamer WHERE id = p_kamer_id FOR UPDATE;
    IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'message', 'Kamer bestaat niet.'); END IF;
    
    SELECT COUNT(*) INTO v_bestaand FROM reservering r JOIN kamer k ON r.kamer_id = k.id WHERE r.persoon_id = p_persoon_id AND k.hotel_id = p_hotel_id;
    IF v_bestaand > 0 THEN RETURN jsonb_build_object('success', false, 'message', 'Je hebt al een kamer gekozen in dit hotel.'); END IF;

    SELECT COUNT(*) INTO v_has_pending FROM reservering WHERE kamer_id = p_kamer_id AND status = 'pending' AND timestamp > (v_server_ts - 60000);
    IF v_has_pending > 0 THEN RETURN jsonb_build_object('success', false, 'message', 'Deze kamer wordt momenteel geconfigureerd door een andere leerling.'); END IF;

    SELECT COUNT(*) INTO v_bezet FROM reservering WHERE kamer_id = p_kamer_id AND status = 'confirmed';
    IF v_bezet >= v_capaciteit THEN RETURN jsonb_build_object('success', false, 'message', 'Deze kamer is vol.'); END IF;

    v_res_id := 'res_' || v_server_ts || '_' || floor(random() * 10000)::int;
    INSERT INTO reservering (id, kamer_id, persoon_id, status, timestamp) VALUES (v_res_id, p_kamer_id, p_persoon_id, 'pending', v_server_ts);
    RETURN jsonb_build_object('success', true, 'res_id', v_res_id, 'server_ts', v_server_ts);
END;
$$;

-- Idem voor bevestig_kamer
DROP FUNCTION IF EXISTS bevestig_kamer(TEXT, TEXT[]);
CREATE OR REPLACE FUNCTION bevestig_kamer(
    p_persoon_id BIGINT,
    p_roommate_ids BIGINT[]
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_res RECORD;
    v_kamer_id BIGINT;
    v_capaciteit INT;
    v_bezet INT;
    v_rm_id BIGINT;
    v_res_id TEXT;
    v_server_ts BIGINT;
BEGIN
    v_server_ts := (extract(epoch from now()) * 1000)::bigint;
    SELECT r.id, r.kamer_id INTO v_res FROM reservering r WHERE r.persoon_id = p_persoon_id AND r.status = 'pending' LIMIT 1;
    IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'message', 'Geen actieve selectie gevonden.'); END IF;
    v_kamer_id := v_res.kamer_id;
    SELECT capaciteit INTO v_capaciteit FROM kamer WHERE id = v_kamer_id FOR UPDATE;
    SELECT COUNT(*) INTO v_bezet FROM reservering WHERE kamer_id = v_kamer_id AND status = 'confirmed';
    IF v_bezet + 1 + coalesce(array_length(p_roommate_ids, 1), 0) > v_capaciteit THEN RETURN jsonb_build_object('success', false, 'message', 'Te veel personen.'); END IF;

    UPDATE reservering SET status = 'confirmed' WHERE id = v_res.id;
    IF p_roommate_ids IS NOT NULL AND array_length(p_roommate_ids, 1) > 0 THEN
        FOREACH v_rm_id IN ARRAY p_roommate_ids LOOP
            v_res_id := 'res_' || v_server_ts || '_' || floor(random() * 10000)::int;
            INSERT INTO reservering (id, kamer_id, persoon_id, status, timestamp) VALUES (v_res_id, v_kamer_id, v_rm_id, 'confirmed', v_server_ts);
        END LOOP;
    END IF;
    RETURN jsonb_build_object('success', true);
END;
$$;
